# Generated by Django 4.2.4 on 2023-08-04 14:07

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(blank=True, max_length=100, null=True)),
                ('current_price', models.DecimalField(blank=True, decimal_places=5, max_digits=10, null=True)),
                ('last_price', models.DecimalField(blank=True, decimal_places=5, max_digits=10, null=True)),
            ],
        ),
    ]
