# Generated by Django 4.2.4 on 2023-08-04 15:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home_depot', '0002_remove_product_name_product_link_product_model_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='model_id',
        ),
    ]
